### ISSUE TITLE
Bootstrap Nav Walker

### ISSUE THREAD

**Issue by mik-laj** [OkveeNet/bootstrap-basic#3]
Helllo friend :smile:
Would you consider using this class?
https://github.com/twittem/wp-bootstrap-navwalker/blob/master/wp_bootstrap_navwalker.php
> This script included the ability to add Bootstrap dividers, dropdown headers, glyphicons and disables links to your menus through the WordPress menu UI. 

And to add support for font awesome for better integration with your themes.

**Comment by ve3** [comment]
That is interesting navbar class, but it is a little far away from 'basic'. 
My idea about this theme is keep everything basic, simple, minimal. 

Just to left the advance space to theme developers to add their own functional. 
In my case I have plan to make child theme with the nav menu walker removed from this theme because I uses [SmartMenus](http://www.smartmenus.org/) which no need any modification in php code, it can use with default WP nav menu walker and also support responsive design.

**Comment by mik-laj** [comment]
Thanks for the clarification. :smile:
Good night
